/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegolamentoRouteImport } from './routes/regolamento'
import { Route as RequestReceivedRouteImport } from './routes/request-received'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ConfirmTokenRouteImport } from './routes/confirm.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegolamentoRoute = RegolamentoRouteImport.update({
  id: '/regolamento',
  path: '/regolamento',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestReceivedRoute = RequestReceivedRouteImport.update({
  id: '/request-received',
  path: '/request-received',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmTokenRoute = ConfirmTokenRouteImport.update({
  id: '/confirm/$token',
  path: '/confirm/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/regolamento': typeof RegolamentoRoute
  '/request-received': typeof RequestReceivedRoute
  '/terms': typeof TermsRoute
  '/confirm/$token': typeof ConfirmTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/regolamento': typeof RegolamentoRoute
  '/request-received': typeof RequestReceivedRoute
  '/terms': typeof TermsRoute
  '/confirm/$token': typeof ConfirmTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/regolamento': typeof RegolamentoRoute
  '/request-received': typeof RequestReceivedRoute
  '/terms': typeof TermsRoute
  '/confirm/$token': typeof ConfirmTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cookies'
    | '/privacy'
    | '/regolamento'
    | '/request-received'
    | '/terms'
    | '/confirm/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cookies'
    | '/privacy'
    | '/regolamento'
    | '/request-received'
    | '/terms'
    | '/confirm/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cookies'
    | '/privacy'
    | '/regolamento'
    | '/request-received'
    | '/terms'
    | '/confirm/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  RegolamentoRoute: typeof RegolamentoRoute
  RequestReceivedRoute: typeof RequestReceivedRoute
  TermsRoute: typeof TermsRoute
  ConfirmTokenRoute: typeof ConfirmTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regolamento': {
      id: '/regolamento'
      path: '/regolamento'
      fullPath: '/regolamento'
      preLoaderRoute: typeof RegolamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-received': {
      id: '/request-received'
      path: '/request-received'
      fullPath: '/request-received'
      preLoaderRoute: typeof RequestReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm/$token': {
      id: '/confirm/$token'
      path: '/confirm/$token'
      fullPath: '/confirm/$token'
      preLoaderRoute: typeof ConfirmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  RegolamentoRoute: RegolamentoRoute,
  RequestReceivedRoute: RequestReceivedRoute,
  TermsRoute: TermsRoute,
  ConfirmTokenRoute: ConfirmTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
